export const Users = [
    {
      id:1,
      profilePicture: "assets/avatar/avatar1.jpeg",
      username: "Maluquete",
    },
    {
      id:2,
      profilePicture: "assets/avatar/avatar2.jpg",
      username: "Romualdo",
    },
    {
      id:3,
      profilePicture: "assets/avatar/avatar3.jpg",
      username: "Alex",
    },
    {
      id:4,
      profilePicture: "assets/avatar/avatar4.jpg",
      username: "Dorate",
    },
    {
      id:5,
      profilePicture: "assets/avatar/avatar5.jpg",
      username: "Thomas",
    },
    {
      id:6,
      profilePicture: "assets/avatar/avatar6.jpg",
      username: "Mariza",
    },
    {
      id:7,
      profilePicture: "assets/avatar/avatar7.jpg",
      username: "Malandro Neves",
    },
    {
      id:8,
      profilePicture: "assets/avatar/avatar8.jpg",
      username: "Fulana",
    }    
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Amei tudo aqui, ja qeuro voltar.",
      photo: "assets/posts/post1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/posts/post2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Gosto muito desse carro.",
      photo: "assets/posts/post3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/posts/post4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/posts/post1.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/posts/post4.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Nuca mais vou ficar aqui nesse lugar.",
      photo: "assets/posts/post3.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/posts/post4.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Vou viajar amanha com minha amiga.",
      photo: "assets/posts/post1.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/posts/post2.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];